### ISSUE TITLE
Save Username

### ISSUE THREAD

**Issue by Praethiax** [BeatPlus/Protonmail#107]
Hi,
I was wondering, if it would be possible to save the Username/Mail address.
I agree that saving the password is not a good idea, but in my oppinion there is no security threat with saving the Username.
I thought it would be a good idea to implement it in the multiple account branche i currently use.

**Comment by BeatPlus** [comment]
Hi, 
I do agree with you and we are working on a new version that saves the mail address. Nevertheless, in the future we will enable a configuration panel in order to make all these features optional. 

If you want to check this feature take a look to enable-multiple-accounts branch.

**Comment by ahoneybun** [comment]
Personally sounds like a feature on the main site more then this portal to it. Maybe I'm wrong?

_Sent from my Huawei Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kontrollanten** [comment]
it's now implemented
