### ISSUE TITLE
[BUG] Prefill username not working on Windows

### ISSUE THREAD

**Issue by BeatPlus** [BeatPlus/Protonmail#116]
No console output, using Win10 and latest master version

I am guessing that the event "dom-ready" activates when Protonmail loading screen appears and attempts to execute the JavaScript provided. At this time the login form did not appear yet and Electron selects an element not created yet.

I would rather avoid setting a timeout, but I could not figure out another solution. I will keep researching

**Comment by kontrollanten** [comment]
One solution could be to create an interval to watch for the element and then run the filling. Maybe not the most beautiful solutions, but I don't know any other way to go.
