### ISSUE TITLE
AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [BeatPlus/Protonmail#43]
Would you be interested to provide an [AppImage](http://appimage.org/) for Linux? electron-builder now has support for it that [makes it really easy](https://github.com/electron-userland/electron-builder/issues/504#issuecomment-233170607) to do.

**Comment by BeatPlus** [comment]
I will take a look into it, but currently I am bussy with work

**Comment by BeatPlus** [comment]
The new branc (0.3.0) yet to be merged adds support for AppImage. Will build this type of package with new releases!
