### ISSUE TITLE
OS X CSS hack

### ISSUE THREAD

**Issue by pwnsdx** [BeatPlus/Protonmail#44]
Hello,

First, thanks for this wrapper! After compiling the app looked weird on OS X so I made some modifications to the CSS and it looks much more better now:

![Before](https://cloud.githubusercontent.com/assets/2057765/17272596/b71abb9e-569a-11e6-9b80-11e8dbc7ec9c.png)
Before

![After](https://cloud.githubusercontent.com/assets/2057765/17272595/b206be28-569a-11e6-8815-256400dc161b.png)
After

Here is the custom CSS code to put in Settings > Appearance:
```
header#pm_header-desktop a.logo img { position:absolute; margin:0; margin-left:-65px; margin-top:50px; padding:0px; }

body section.sidebar { padding-top:35px; }

header#pm_header-desktop, #pm_settings .pm_tabs { background:#505061; }
```

Cheers

**Comment by pwnsdx** [comment]
It's only intended for OS X so this code should do the trick

```
if (process.platform === 'darwin') {
	page.insertCSS(fs.readFileSync(path.join(__dirname, 'themes/osx-fix.css'), 'utf8'));
}
```

**Comment by BeatPlus** [comment]
It should be working right now, reopen it if needed. Thank you

**Comment by pwnsdx** [comment]
Unfortunately it don't work as excepted when directly injected in the page (I have the same view as you) but it works well when I put the CSS in "Settings > Appearance > Custom theme" :/

**Comment by BeatPlus** [comment]
Could you check now? I tried a workaround

**Comment by pwnsdx** [comment]
There was a typo (margin) but it worked so here is the final fix:

```
header#pm_header-desktop a.logo img {
    margin-top: 40px!important;
}
body section.sidebar {
	padding-top: 20px!important;
}
header#pm_header-desktop,
#pm_settings .pm_tabs {
	background: #505061!important;
}
```

Thanks you!

**Comment by BeatPlus** [comment]
I just committed new changes. Thank you
