### ISSUE TITLE
Downloading a file does not function

### ISSUE THREAD

**Issue by Xalaxis** [BeatPlus/Protonmail#47]
Attempting to download an attachment seems to download the attachment but it is not opened nor stored anywhere obvious.

**Comment by dumle29** [comment]
Same problem observed
Ubuntu gnome 16.04

**Comment by BeatPlus** [comment]
It should download to user ´Download´ directory, code comes from ´sindresorhus/electron-dl´. It seem tlike he plugin was updated to use Save as dialog, but unfortunately I cannot commit until I get back to my country. If anyone can PR I will merge it!

**Comment by Xalaxis** [comment]
I've just double checked and it does seem to be saving to the system download directory, as you pointed out though, without a save-as dialog or even a message stating this it's a very confusing experience for the end-user.

**Comment by HaydenSD** [comment]
Attempting a fix for this.

**Comment by HaydenSD** [comment]
Oh awesome, ty @BeatPlus!
