### ISSUE TITLE
Bundle code from WebClient

### ISSUE THREAD

**Issue by emersion** [BeatPlus/Protonmail#48]
A problem with the webapp is that the source code is served from ProtonMail's servers, thus could be modified if ProtonMail was forced to. That would allow ProtonMail to get login and mailbox passwords.

A solution would be to bundle the webapp code from https://github.com/ProtonMail/WebClient directly in this app.

**Comment by BeatPlus** [comment]
Hi,
That would be a great idea from a security prespective, but there is a big issue; it is really complex. Implementing the webclient with electron would take so much time I do not have now. 
Anyway, that should be an independent project, this repo clearly stated to be a Protonmail wrapper.

**Comment by emersion** [comment]
You don't need to implement a WebClient since it's open-source. You just need to include https://giyhub/ProtonMail/WebClient in the build. It's really easy.
