### ISSUE TITLE
OSX Client doesn't remember me

### ISSUE THREAD

**Issue by kristiyandobrev** [BeatPlus/Protonmail#50]
I have just noticed that the OSX client requires me to log in again every time I close the app (cmd+q). Is that an intended behavior?

**Comment by HaydenSD** [comment]
Yes, ProtonMail doesn't save credentials. Only a browser like Google Chrome does, and that doesn't keep the log in.

**Comment by BeatPlus** [comment]
Exactly, for security reasons protonmail does not save the session, and
there is no intention to change this behavior.
