### ISSUE TITLE
Window not moveable on OSX

### ISSUE THREAD

**Issue by braindump** [BeatPlus/Protonmail#51]
In macOS Sierra, I'm not able to move the window around by dragging the menu bar.

**Comment by HaydenSD** [comment]
I'll compile the latest version and take a look at this.

**Comment by BeatPlus** [comment]
If I am right, I believe this is because on MacOS there is no window frame, therefore no moveable. I cannot perform tests on MacOS, but if this is still a bug I will attempt to fix it. 
@braindump or @HaydenSD Would you mind testing for me once I commit the fix?

**Comment by braindump** [comment]
Sure, can do.

**Comment by tnguyen** [comment]
I'm trying out the current version and i'm able to move the window by click/dragging the topmost pixel.

**Comment by BeatPlus** [comment]
@braindump if the last version fixes this bug, i'll proceed to close the issue

**Comment by kontrollanten** [comment]
@braindump @thien Can you try to pull my fork and see if it works for you? https://github.com/kontrollanten/Protonmail
