### ISSUE TITLE
Javascript error (Mac)

### ISSUE THREAD

**Issue by ajkblue** [BeatPlus/Protonmail#54]
When launching the latest version of ProtonMail Desktop I get this error:
![screen shot 2017-01-16 at 2 30 22 pm](https://cloud.githubusercontent.com/assets/9651939/21999775/ec8cdf26-dbf8-11e6-9255-606f626c4cfd.png)

**Comment by BeatPlus** [comment]
Cons of not having a mac. Should be fixed.
