### ISSUE TITLE
Adding unread mail count on traybar

### ISSUE THREAD

**Issue by dslul** [BeatPlus/Protonmail#87]
Given that this is a web app, is it possible to implement this?

**Comment by BeatPlus** [comment]
You mean to display the number of unread emails on the traybar?

**Comment by dslul** [comment]
Yes, is it feasible?

**Comment by BeatPlus** [comment]
It might by feasible, but to my understanding electron updates the badge with a static image when a new email arrives, we would need an undefined amount of static images which might not be desired. 
If there is a a better way to do this I will implement it, I will take a look into it.

**Comment by kontrollanten** [comment]
@BeatPlus Isn't it supposed that updateBadge function should handle this with app.dock.setBadge()? 

```function updateBadge(messageCount) {
    // Set badge
    if (process.platform === 'darwin') {
        app.dock.setBadge(messageCount ? messageCount[1] : '');
    } else {
        tray.setBadge(messageCount);
    }
```

As far as I understand from reading the code the updateBadge function isn't ran when a new message has arrived. 

```
function checkMessages(title) {
    // Update badge
    // How many new messages on new title?
    const messageCount = (/\(([0-9]+)\)/).exec(title);
    // How many messages I had?
    const messageCountOld = (/\(([0-9]+)\)/).exec(oldtitle);

    // No unread messages, do nothing than setting badge to 0
    if (!messageCount) {
        const indexCount = (/inbox/i).exec(title);
        if (indexCount) {
            oldtitle = 0;
            updateBadge(0);
        }
        return;
    }

    // No new messages, do nothing.
    if (messageCountOld && messageCount[1] <= messageCountOld[1]) {
        updateBadge(0);
        return;
    }

    oldtitle = title;
}
```

Why can't we just change checkMessage function to the following? 

```
function checkMessages(title) {
    const messageCount = (/\(([0-9]+)\)/).exec(title);
    updateBadge(messageCount);
}
```

I've tested it locally (Mac OS) and it's working brilliant. Please let me know if you want a PR for this.

**Comment by BeatPlus** [comment]
@kontrollanten Your code seems right to me, I've been testing it and seems to work correctly. 

The reason I wrote this ugly workaround was mainly because Protonmail did not implement notifications until v3.3. Due to lack of time I did not updated to the right way, it just "worked". I will happily accept your PR
