### ISSUE TITLE
Build without a github token

### ISSUE THREAD

**Issue by Keepco** [BeatPlus/Protonmail#92]
Hello,

I guess this is pretty trivial, but I'm still pretty new to the JS universe :)

Is it possible to build this package without a Github token? I can't seem to find anything about it on electron-builder's wiki.

**Comment by BeatPlus** [comment]
Hi @Keepco,
What do you mean by building without a Github token? The process does not require any token, and signing the binary is only optional.

**Comment by Keepco** [comment]
Hello,

maybe I'm just doing it wrong, but if I run 'npm install' && 'npm run release' the build process fails with 'Error: Publish is set to always, but neither GH_TOKEN nor BT_TOKEN is not set.
